### ISSUE TITLE
[Bug] RepositoryImpl

### ISSUE THREAD

**Issue by hyeonji91** [Namo-Mongmong/Server#22]
## **⛔️Bug**

- Repository 인터페이스가 RepositoryImpl를 찾지 못함
## **Bug Situation**

1.  PropertyReferenceException: No property 'findOneSchedule' found for type 'Schedule'

## **Expected behavior**

@Repostiory 어노테이션의 부재

## **Screenshots**

![image](https://github.com/Namo-Mongmong/Server/assets/112065014/81ba1a70-afb7-4bba-9fac-b5f66115d6d9)

**Comment by galug** [comment]
이 부분에 대해서는 아마 디렉 토리 위치를 잘못 설정하신 것 같습니다. Impl 클래스가 
![image](https://github.com/Namo-Mongmong/Server/assets/41482946/e386337c-0b6b-40aa-99d3-6dc7c39be861)
이런 식으로 같은 디렉터리 내에 존재하지 않으면 Spring 이 인식을 못해서 저런 오류가 납니다

**Comment by luke0408** [comment]
#21 해당 pr을 통해 해결됨
